import { useState } from "react";
import { Link as RouterLink } from "react-router-dom";

// material
import { styled } from "@material-ui/core/styles";
import RemoveIcon from "@material-ui/icons/Remove";
import AddIcon from "@material-ui/icons/Add";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Autoplay } from "swiper/core";

import {
  Box,
  Grid,
  Container,
  Typography,
  Button,
  Stack,
  Divider,
  Accordion as MuiAccordion,
  AccordionSummary as MuiAccordionSummary,
  AccordionDetails as MuiAccordionDetails,
} from "@material-ui/core";
//
import { varFadeInUp, MotionInView, varFadeInDown } from "../../animate";
import Card from "../../Card";

SwiperCore.use([Autoplay]);

// ----------------------------------------------------------------------

const RootStyle = styled("div")(({ theme }) => ({
  paddingTop: theme.spacing(15),
  [theme.breakpoints.up("md")]: {
    paddingBottom: theme.spacing(15),
  },
}));

export default function LandingMinimalHelps() {
  const [expanded, setExpanded] = useState("panel1");

  const handleChange = (panel) => (event, newExpanded) => {
    setExpanded(newExpanded ? panel : false);
  };
  return (
    <RootStyle>
      <Box sx={{ px: { xs: 3, md: 24 } }}>
        <Box sx={{ mb: { xs: 10, md: 10 }, mt: 10 }}>
          <MotionInView variants={varFadeInUp}>
            <Box sx={{ py: 5, pr: 8, width: 1 }}>
              <Typography variant="h2">TERMS</Typography>
              <Typography variant="body1" sx={{ mt: 5 }}>
                Degenerate Ape Academy is a collection of digital artworks
                (NFTs) running on the Solana network. This website is only an
                interface allowing participants to exchange digital
                collectibles. Users are entirely responsible for the safety and
                management of their own private Solana wallets and validating
                all transactions and contracts generated by this website before
                approval. Furthermore, as the Degenerate Ape Academy smart
                contract runs on the Solana network, there is no ability to
                undo, reverse, or restore any transactions.
              </Typography>
              <Typography variant="body1" sx={{ mt: 3 }}>
                This website and its connected services are provided “as is” and
                “as available” without warranty of any kind. By using this
                website you are accepting sole responsibility for any an all
                transactions involving Degenerate Ape Academy digital
                collectibles.
              </Typography>
            </Box>
          </MotionInView>
          <MotionInView variants={varFadeInUp}>
            <Box sx={{ py: 5, pr: 8, width: 1 }}>
              <Typography variant="h2">OWNERSHIP</Typography>
              <Typography variant="body1" sx={{ mt: 5 }}>
                Degenerate Ape Academy is a collection of digital artworks
                (NFTs) running on the Solana network. This website is only an
                interface allowing participants to exchange digital
                collectibles. Users are entirely responsible for the safety and
                management of their own private Solana wallets and validating
                all transactions and contracts generated by this website before
                approval. Furthermore, as the Degenerate Ape Academy smart
                contract runs on the Solana network, there is no ability to
                undo, reverse, or restore any transactions.
              </Typography>
              <Typography variant="body1" sx={{ mt: 3 }}>
                This website and its connected services are provided “as is” and
                “as available” without warranty of any kind. By using this
                website you are accepting sole responsibility for any an all
                transactions involving Degenerate Ape Academy digital
                collectibles.
              </Typography>
            </Box>
          </MotionInView>
        </Box>
      </Box>
    </RootStyle>
  );
}
